export default [
  {
    id: 17,
    name: "Ngân hàng TMCP Công thương Việt Nam",
    code: "ICB",
    bin: "970415",
    shortName: "VietinBank",
    logo: "https://api.vietqr.io/img/ICB.png",
    transferSupported: 1,
    lookupSupported: 1,
    short_name: "VietinBank",
    support: 3,
    isTransfer: 1,
    swift_code: "ICBVVNVX",
  },
  {
    id: 43,
    name: "Ngân hàng TMCP Ngoại Thương Việt Nam",
    code: "VCB",
    bin: "970436",
    shortName: "Vietcombank",
    logo: "https://api.vietqr.io/img/VCB.png",
    transferSupported: 1,
    lookupSupported: 1,
    short_name: "Vietcombank",
    support: 3,
    isTransfer: 1,
    swift_code: "BFTVVNVX",
  },
  {
    id: 4,
    name: "Ngân hàng TMCP Đầu tư và Phát triển Việt Nam",
    code: "BIDV",
    bin: "970418",
    shortName: "BIDV",
    logo: "https://api.vietqr.io/img/BIDV.png",
    transferSupported: 1,
    lookupSupported: 1,
    short_name: "BIDV",
    support: 3,
    isTransfer: 1,
    swift_code: "BIDVVNVX",
  },
  {
    id: 42,
    name: "Ngân hàng Nông nghiệp và Phát triển Nông thôn Việt Nam",
    code: "VBA",
    bin: "970405",
    shortName: "Agribank",
    logo: "https://api.vietqr.io/img/VBA.png",
    transferSupported: 1,
    lookupSupported: 1,
    short_name: "Agribank",
    support: 3,
    isTransfer: 1,
    swift_code: "VBAAVNVX",
  },
  {
    id: 26,
    name: "Ngân hàng TMCP Phương Đông",
    code: "OCB",
    bin: "970448",
    shortName: "OCB",
    logo: "https://api.vietqr.io/img/OCB.png",
    transferSupported: 1,
    lookupSupported: 1,
    short_name: "OCB",
    support: 3,
    isTransfer: 1,
    swift_code: "ORCOVNVX",
  },
  {
    id: 21,
    name: "Ngân hàng TMCP Quân đội",
    code: "MB",
    bin: "970422",
    shortName: "MBBank",
    logo: "https://api.vietqr.io/img/MB.png",
    transferSupported: 1,
    lookupSupported: 1,
    short_name: "MBBank",
    support: 3,
    isTransfer: 1,
    swift_code: "MSCBVNVX",
  },
  {
    id: 2,
    name: "Ngân hàng TMCP Á Châu",
    code: "ACB",
    bin: "970416",
    shortName: "ACB",
    logo: "https://api.vietqr.io/img/ACB.png",
    transferSupported: 1,
    lookupSupported: 1,
    short_name: "ACB",
    support: 3,
    isTransfer: 1,
    swift_code: "ASCBVNVX",
  },
  {
    id: 39,
    name: "Ngân hàng TMCP Tiên Phong",
    code: "TPB",
    bin: "970423",
    shortName: "TPBank",
    logo: "https://api.vietqr.io/img/TPB.png",
    transferSupported: 1,
    lookupSupported: 1,
    short_name: "TPBank",
    support: 3,
    isTransfer: 1,
    swift_code: "TPBVVNVX",
  },
  {
    id: 12,
    name: "Ngân hàng TMCP Phát triển Thành phố Hồ Chí Minh",
    code: "HDB",
    bin: "970437",
    shortName: "HDBank",
    logo: "https://api.vietqr.io/img/HDB.png",
    transferSupported: 1,
    lookupSupported: 1,
    short_name: "HDBank",
    support: 3,
    isTransfer: 1,
    swift_code: "HDBCVNVX",
  },
  {
    id: 31,
    name: "Ngân hàng TMCP Sài Gòn",
    code: "SCB",
    bin: "970429",
    shortName: "SCB",
    logo: "https://api.vietqr.io/img/SCB.png",
    transferSupported: 1,
    lookupSupported: 1,
    short_name: "SCB",
    support: 3,
    isTransfer: 1,
    swift_code: "SACLVNVX",
  },
  {
    id: 45,
    name: "Ngân hàng TMCP Quốc tế Việt Nam",
    code: "VIB",
    bin: "970441",
    shortName: "VIB",
    logo: "https://api.vietqr.io/img/VIB.png",
    transferSupported: 1,
    lookupSupported: 1,
    short_name: "VIB",
    support: 3,
    isTransfer: 1,
    swift_code: "VNIBVNVX",
  },
  {
    id: 35,
    name: "Ngân hàng TMCP Sài Gòn - Hà Nội",
    code: "SHB",
    bin: "970443",
    shortName: "SHB",
    logo: "https://api.vietqr.io/img/SHB.png",
    transferSupported: 1,
    lookupSupported: 1,
    short_name: "SHB",
    support: 3,
    isTransfer: 1,
    swift_code: "SHBAVNVX",
  },
  {
    id: 53,
    name: "TMCP Việt Nam Thịnh Vượng - Ngân hàng số CAKE by VPBank",
    code: "CAKE",
    bin: "546034",
    shortName: "CAKE",
    logo: "https://api.vietqr.io/img/CAKE.png",
    transferSupported: 1,
    lookupSupported: 1,
    short_name: "CAKE",
    support: 3,
    isTransfer: 1,
    swift_code: null,
  },
  {
    id: 57,
    name: "Tổng Công ty Dịch vụ số Viettel - Chi nhánh tập đoàn công nghiệp viễn thông Quân Đội",
    code: "VTLMONEY",
    bin: "971005",
    shortName: "ViettelMoney",
    logo: "https://api.vietqr.io/img/VIETTELMONEY.png",
    transferSupported: 0,
    lookupSupported: 1,
    short_name: "ViettelMoney",
    support: 0,
    isTransfer: 0,
    swift_code: null,
  },
  {
    id: 56,
    name: "VNPT Money",
    code: "VNPTMONEY",
    bin: "971011",
    shortName: "VNPTMoney",
    logo: "https://api.vietqr.io/img/VNPTMONEY.png",
    transferSupported: 0,
    lookupSupported: 1,
    short_name: "VNPTMoney",
    support: 0,
    isTransfer: 0,
    swift_code: null,
  },
  {
    id: 34,
    name: "Ngân hàng TMCP Sài Gòn Công Thương",
    code: "SGICB",
    bin: "970400",
    shortName: "SaigonBank",
    logo: "https://api.vietqr.io/img/SGICB.png",
    transferSupported: 1,
    lookupSupported: 1,
    short_name: "SaigonBank",
    support: 3,
    isTransfer: 1,
    swift_code: "SBITVNVX",
  },
  {
    id: 3,
    name: "Ngân hàng TMCP Bắc Á",
    code: "BAB",
    bin: "970409",
    shortName: "BacABank",
    logo: "https://api.vietqr.io/img/BAB.png",
    transferSupported: 1,
    lookupSupported: 1,
    short_name: "BacABank",
    support: 3,
    isTransfer: 1,
    swift_code: "NASCVNVX",
  },
  {
    id: 30,
    name: "Ngân hàng TMCP Đại Chúng Việt Nam",
    code: "PVCB",
    bin: "970412",
    shortName: "PVcomBank",
    logo: "https://api.vietqr.io/img/PVCB.png",
    transferSupported: 1,
    lookupSupported: 1,
    short_name: "PVcomBank",
    support: 3,
    isTransfer: 1,
    swift_code: "WBVNVNVX",
  },
  {
    id: 27,
    name: "Ngân hàng Thương mại TNHH MTV Đại Dương",
    code: "Oceanbank",
    bin: "970414",
    shortName: "Oceanbank",
    logo: "https://api.vietqr.io/img/OCEANBANK.png",
    transferSupported: 1,
    lookupSupported: 1,
    short_name: "Oceanbank",
    support: 3,
    isTransfer: 1,
    swift_code: "OCBKUS3M",
  },
  {
    id: 24,
    name: "Ngân hàng TMCP Quốc Dân",
    code: "NCB",
    bin: "970419",
    shortName: "NCB",
    logo: "https://api.vietqr.io/img/NCB.png",
    transferSupported: 1,
    lookupSupported: 1,
    short_name: "NCB",
    support: 3,
    isTransfer: 1,
    swift_code: "NVBAVNVX",
  },
  {
    id: 37,
    name: "Ngân hàng TNHH MTV Shinhan Việt Nam",
    code: "SHBVN",
    bin: "970424",
    shortName: "ShinhanBank",
    logo: "https://api.vietqr.io/img/SHBVN.png",
    transferSupported: 1,
    lookupSupported: 1,
    short_name: "ShinhanBank",
    support: 3,
    isTransfer: 1,
    swift_code: "SHBKVNVX",
  },
  {
    id: 1,
    name: "Ngân hàng TMCP An Bình",
    code: "ABB",
    bin: "970425",
    shortName: "ABBANK",
    logo: "https://api.vietqr.io/img/ABB.png",
    transferSupported: 1,
    lookupSupported: 1,
    short_name: "ABBANK",
    support: 3,
    isTransfer: 1,
    swift_code: "ABBKVNVX",
  },
  {
    id: 41,
    name: "Ngân hàng TMCP Việt Á",
    code: "VAB",
    bin: "970427",
    shortName: "VietABank",
    logo: "https://api.vietqr.io/img/VAB.png",
    transferSupported: 1,
    lookupSupported: 1,
    short_name: "VietABank",
    support: 3,
    isTransfer: 1,
    swift_code: "VNACVNVX",
  },
  {
    id: 29,
    name: "Ngân hàng TMCP Xăng dầu Petrolimex",
    code: "PGB",
    bin: "970430",
    shortName: "PGBank",
    logo: "https://api.vietqr.io/img/PGB.png",
    transferSupported: 1,
    lookupSupported: 1,
    short_name: "PGBank",
    support: 3,
    isTransfer: 1,
    swift_code: "PGBLVNVX",
  },
  {
    id: 46,
    name: "Ngân hàng TMCP Việt Nam Thương Tín",
    code: "VIETBANK",
    bin: "970433",
    shortName: "VietBank",
    logo: "https://api.vietqr.io/img/VIETBANK.png",
    transferSupported: 1,
    lookupSupported: 1,
    short_name: "VietBank",
    support: 3,
    isTransfer: 1,
    swift_code: "VNTTVNVX",
  },
  {
    id: 5,
    name: "Ngân hàng TMCP Bảo Việt",
    code: "BVB",
    bin: "970438",
    shortName: "BaoVietBank",
    logo: "https://api.vietqr.io/img/BVB.png",
    transferSupported: 1,
    lookupSupported: 1,
    short_name: "BaoVietBank",
    support: 3,
    isTransfer: 1,
    swift_code: "BVBVVNVX",
  },
  {
    id: 52,
    name: "Ngân hàng Hợp tác xã Việt Nam",
    code: "COOPBANK",
    bin: "970446",
    shortName: "COOPBANK",
    logo: "https://api.vietqr.io/img/COOPBANK.png",
    transferSupported: 1,
    lookupSupported: 1,
    short_name: "COOPBANK",
    support: 3,
    isTransfer: 1,
    swift_code: null,
  },
  {
    id: 20,
    name: "Ngân hàng TMCP Bưu Điện Liên Việt",
    code: "LPB",
    bin: "970449",
    shortName: "LienVietPostBank",
    logo: "https://api.vietqr.io/img/LPB.png",
    transferSupported: 1,
    lookupSupported: 1,
    short_name: "LienVietPostBank",
    support: 3,
    isTransfer: 1,
    swift_code: "LVBKVNVX",
  },
  {
    id: 19,
    name: "Ngân hàng TMCP Kiên Long",
    code: "KLB",
    bin: "970452",
    shortName: "KienLongBank",
    logo: "https://api.vietqr.io/img/KLB.png",
    transferSupported: 1,
    lookupSupported: 1,
    short_name: "KienLongBank",
    support: 3,
    isTransfer: 1,
    swift_code: "KLBKVNVX",
  },
  {
    id: 32,
    name: "Ngân hàng TNHH MTV Standard Chartered Bank Việt Nam",
    code: "SCVN",
    bin: "970410",
    shortName: "StandardChartered",
    logo: "https://api.vietqr.io/img/SCVN.png",
    transferSupported: 0,
    lookupSupported: 1,
    short_name: "StandardChartered",
    support: 0,
    isTransfer: 0,
    swift_code: "SCBLVNVX",
  },
  {
    id: 28,
    name: "Ngân hàng TNHH MTV Public Việt Nam",
    code: "PBVN",
    bin: "970439",
    shortName: "PublicBank",
    logo: "https://api.vietqr.io/img/PBVN.png",
    transferSupported: 0,
    lookupSupported: 1,
    short_name: "PublicBank",
    support: 0,
    isTransfer: 0,
    swift_code: "VIDPVNVX",
  },
  {
    id: 18,
    name: "Ngân hàng TNHH Indovina",
    code: "IVB",
    bin: "970434",
    shortName: "IndovinaBank",
    logo: "https://api.vietqr.io/img/IVB.png",
    transferSupported: 0,
    lookupSupported: 1,
    short_name: "IndovinaBank",
    support: 0,
    isTransfer: 0,
    swift_code: null,
  },
  {
    id: 49,
    name: "Ngân hàng TNHH MTV Woori Việt Nam",
    code: "WVN",
    bin: "970457",
    shortName: "Woori",
    logo: "https://api.vietqr.io/img/WVN.png",
    transferSupported: 1,
    lookupSupported: 1,
    short_name: "Woori",
    support: 0,
    isTransfer: 1,
    swift_code: null,
  }
];
